name: image_picker_web
description: Flutter Web Plugin to pick Images (as Widget or Uint8List) and Videos (as Uint8List)
version: 0.1.6
author: Rebar Ahmad <rebar.ahmad@gmail.com>
homepage: https://github.com/Ahmadre
repository: https://github.com/Ahmadre/image_picker_web

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      web:
        pluginClass: ImagePickerWeb
        fileName: image_picker_web.dart
